[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@ccip/contracts/=lib/ccip/contracts/",
    "@chainlink-local/=lib/chainlink-local/"
]
rpc_endpoints = {sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}", arb-sepolia = "https://arb-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}", zk-sepolia = "https://zksync-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"}

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
